### ISSUE TITLE
Image previews

### ISSUE THREAD

**Issue by medienbaecker** [medienbaecker/kirby-quickselect#2]

**Comment by medienbaecker** [comment]
@jenstornell: I've added the feature we previously talked about on the [develop](https://github.com/medienbaecker/kirby-quickselect/tree/develop) branch.

![quickselect](https://cloud.githubusercontent.com/assets/7975568/20968105/0a9f2d10-bc83-11e6-9132-f6a2feb1ac5e.gif)

When there are images in the options, the field automatically generates previews for them.

It's pretty helpful already, but there's one thing I don't like.
The field creates thumbnails for the images and slows down the panel on the first load, just like the visual file selector or similar plugins. Do you have a better solution for that?

**Comment by jenstornell** [comment]
It looks kind of like the image field, but better! :)

Does this field slow down when the images are visible or even when they are invisible? If they are generated just when the becomes visible I think it's fine. It's called progessive enhancement.

If they will all load at the same time I think it's an issue with many images. A solution could be the use background images, then they will only load when they are visible.

But I guess the problem is about the PHP generation side of it. If the plugin is already using Ajax you could maybe use that.

But it can be a tricky one to solve without ajax, maybe impossible.

**Comment by medienbaecker** [comment]
The frontend does not slow down, it's just the thumbnail creation when the page first loads. And only the first time obviously. But I hate to affect the beloved snappiness of the Kirby panel.

I'm going to have a look at the Ajax suggestion, asynchronous thumbnails are a lot better in this case. Thank you!

**Comment by jenstornell** [comment]
Ajax is probably the best solution but I've figured out that an iframe would work as well. Then the iframe would load async with the panel.

**Comment by medienbaecker** [comment]
Ok, that sounds simpler than the Ajax solution. How would you start the thumbnail progress with an iframe, though? Or how do you get the source of the thumbnail without the `<img>`?

**Comment by jenstornell** [comment]
Both Ajax and Iframes are tricky in their own way. I often Google each question and after a few hours I often solve the problem.

Did the Imagekit solve this problem? In that case, to be lazy, just add "Require Imagekit" ;)

**Comment by medienbaecker** [comment]
ImageKit definitely solved the problem. I think this is probably an issue of the Kirby panel itself. Thanks for you help @jenstornell

**Comment by jenstornell** [comment]
I hope like you that they solve it in the panel core. The animated gif looked really nice. Load the panel fast, and later fill it with the images.

**Comment by medienbaecker** [comment]
Sadly I didn't get any answers or even just some information yet. Same with the other major issue https://github.com/getkirby/panel/issues/185

ImageKit actually produces exactly that, just like in the animated gif. I don't know how to justify additional the 30 Euros to my clients, yet. But it seems like a must-have plugin right now.
