### ISSUE TITLE
Too wide images

### ISSUE THREAD

**Issue by jenstornell** [medienbaecker/kirby-quickselect#5]
The really good new is that this plugin works great with Engineer! :smile:

But I get too wide image previews.

![localhost-engineer-panel-pages-engineer-edit](https://user-images.githubusercontent.com/927011/27436213-d77d6416-575e-11e7-9400-480a9895088d.png)

The first quickselect field is not inside an Engineer field so it seems to be something else. In the dropdown the size is correct. My images are not perfectly squared, maybe that's why? Because the built in image field uses square images no matter what I think this should too?

**Comment by jenstornell** [comment]
Also I don't get any image label. I disabled all other plugins but I get the same results. I use Kirby 2.5.1.

**Comment by medienbaecker** [comment]
That was a simple CSS error in the last commit. Very sorry about that, I just fixed it and also added a `package.json`.

**Comment by jenstornell** [comment]
I can confirm that it works and it's also 100% compatible to Engineer. 😄
