### ISSUE TITLE
Error installing via the commandline

### ISSUE THREAD

**Issue by wout** [medienbaecker/kirby-quickselect#6]
I tried to install this plugin using the command line:

```cli
kirby plugin:install medienbaecker/kirby-quickselect
```

But I got the following error:

```cli
[RuntimeException]         
Invalid Kirby Plugin Type
```

Your fieldtoggle plugin installs without a problem.

**Comment by medienbaecker** [comment]
I just realized the `package.json` was called `packages.json`. I updated the file name — can you check if it works for you now?
